<div class="header-bottom">
    <div class="container">
        <div class="logo wow fadeInDown"  data-wow-duration=".8s" data-wow-delay=".2s">            
            <h1><a href="#">Nainital - an Introduction</a></a></h1>
        </div>
    </div>
</div>
<div class="technology">
    <div class="container">
        <div class="col-md-12">            
            <div style="padding:30px; background: #fff;">
                <p align="justify"><img src="<?PHP echo base_url() . 'nitnav/images/t5.jpg'; ?>" class="img-responsive col-sm-8" alt="nainital" style="padding:1em;float:left;">Ensconced snugly at an altitude of 1938 metres above sea level, Nainital has made a tryst with fame in being the country’s most popular hill station. Situated at (29.3803° N, 79.4636° E) the geological fault line between Naini-Sher Ka Danda ridge and Ayarpatta block give Nainital its famous Naini lake.</p>                
                <p align="justify" style="margin-bottom: 10px;">The ancient name of Nainital is Tri- Rishi Sarovar, after the three sages, Atri, Agastya and Pulaha. It is believed that they came here on a penitential pilgrimage while going to Mansarovar, the holy lake in Tibet. On finding no water for drinking, they dug a large hole and siphoned water from Mansarovar with their divine powers. Thus the ancient Indians believed that a dip in the Naini Lake earned the same religious merit as a holy dip in the Mansarovar Lake. The second important religious reference to Nainital is as one of the 64 Shakti Peeths, i.e. centres of spiritual powers. These centres were created wherever remnants of Goddess Sati fell, when Lord Shiva was carrying her body in grief. It is said that the left eye (Nain) of Goddess Sati dropped here which in turn gives the lake and the city its name. The town has therefore been a centre of religious and spiritual importance for a very long time.</p>
                <p align="justify" style="margin-bottom: 10px;">The British occupied Kumaon and Garhwal in 1815. After the British occupation, Edward Gardener was appointed as the first Commissioner of Kumaon Division till 13th April 1816. He was succeeded by George William Traill who was the first European to have visited Nainital while conducting the revenue settlement of 1823. He however refrained from popularizing it for love for the Kumaoni culture and and fear that it might be desecrated and corrupted by outside influence. P. Barron who visited Nainital in 1841 consequently wrote about it in his book, ‘Wanderings in the Himmala’.</p>
                <p align="justify" style="margin-bottom: 10px;">The credit of initiating urban development in Nainital goes to Commissioner of Kumaon, George Thomas Lushington , P. Barron and Moti Ram Sah. By 1847 according to the historical records, it had become popular as a health/tourist resort for the British. The first bungalow ‘Sherwood House’ was built for Major Arnaud in 1843 who was leased 280 acres of land in Gaiwala Khet (cow’s field) or Gwali Khet, Raj Bhawan area. On 3rd October 1850, the Naini Tal Municipal Board was formally constituted. It was the second Municipal Board of the North Western Provinces and its Bye Laws approved in July 1851 were one of the best in the country. Mohan Lal Sah the freedom fighter and banker, was elected as its first Indian Chairman in 1935-36 and Sheikh Abdul Kayyum was its senior Vice Chairman. In October 1855 the Commissioner’s office was transferred from Almora to Naini Tal owing to its proximity to the plains. The credit of establishing the Commissioner’s office goes to Henry Ramsay though his predecessor, John Hallet Batten had already purchased and repaired Ousley Grove for the Commissioner’s office and Kutcherry in Naini Tal.</p>
                <p align="justify" style="margin-bottom: 10px;">The hill town assumed a great importance after 1857 as there was no outbreak of disorder here and served as a safe hide out for the refugees from the neighbouring plains. Moti Ram Sah played an important in helping the British financially in addition to providing valuable intelligence. In 1862 Nainital was made the summer seat of the North Western Provinces and a great educational centre for British children. Mission School where the present CRST Intermediate College is located is the oldest educational institution in Nainital, established in 1850. Concomitantly Sherwood College (1867), All Saints’ College (1869) and St. Mary’s Convent (1878) came into existence. Subsequently the Philanders Smith College now known as Birla Vidya Mandir was established as a result of the amalgamation of Philanders Smith College transferred from Mussorie to Nainital in 1905 and the Oak Openings Boys’ High School, already established in Nainital in 1877. Wellesley Girls High School was started in 1882. After Independence this premier institution was purchased by the philanthropist, Th. Dan Singh Bisht. He donated the building and five lakh rupees with about 12 acres of land to the government for starting a degree college in Nainital. The poor students from the towns and villages of Uttarakhand found it difficult to go to Allahabad or Lucknow for higher education and thus he rendered a yeoman service in the field of higher education. Today the academic block of Kumaon University is housed there.</p>
                <p align="justify" style="margin-bottom: 10px;">Gradually Nainital also became an important centre of trade and banking facilities were provided. In the 1880s the Bank of Upper India was established which consequently became State Bank of India. After the establishment of the Bank of Upper India, the Allahabad Bank was established in 1892 followed by Nainital Bank and the Durga Lal Sah Mohan Lal Sah. The importance of the town was further boosted with the installation of the rail link to Kathgodam from Bareilly on 24th October 1884. The Nainital district was formed in 1891 which was followed by completion of the water supply scheme was in 1899. The Talli Tal Post Office came into existence in 1896 and the Malli Tal Post Office in 1903. In 1911-12 Naini Tal was amongst a few privileged cities of the country where telephone services were available.</p>
                <p align="justify" style="margin-bottom: 10px;">In 1905, Naini Tal became the Headquarters of the Eastern Command and in 1908 the summer laboratory of Chemical Examiner was established in the Stone Leigh compound. In 1913 it was upgraded to Senior Chemical Examiner Laboratory. Later it was shifted to Karachi and finally to Poona as High Energy Material Laboratory. The completion of a motor road between Kathgodam and Naini Tal in 1915 further contributed to the growth of the town. The first printing press, King Press was established in Naini Tal in 1919. In 1922, the electrification scheme was initiated for the town of Nainital.</p>
                <p align="justify" style="margin-bottom: 10px;">After Independence in 1960 the Uttar Pradesh Government decided not to shift the capital to Naini Tal during summers, and in the initial stages this proved a great set back to the economy of the town and district. It was however facilitated by the development of a tourist resort in 1972. In October 1995 Udham Singh Nagar was carved out of Naini Tal district named after Shaeed –i-Azam, Udham Singh a great revolutionary. With the formation of the State of Uttarakhand, tourism has been given a big fillip which has brought in greater economic opportunities for the locals. This has in turn created a new challenge of retaining the aesthetic beauty and ecological purity of this unique city.</p>                
                <p><span style="font-size: 18px;">(Content Courtesy -  Ajay S. Rawat)</span></p>
                <div class="clearfix"></div>
            </div>                               
            <div class="clearfix"></div>
            <!-- technology-right -->
        </div>                     
        <!-- technology-right -->
    </div>
</div>